# Generated by Django 5.2.4 on 2025-07-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='extracted_skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
