# Generated by Django 5.2.4 on 2025-07-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_remove_resume_user_alter_resume_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='extracted_skills',
            new_name='skills',
        ),
    ]
